let ActionTypes = {
    GET_TODOS: 'GET_TODOS',
    GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
    GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',

    GET_TODO: 'GET_TODO',
    GET_TODO_SUCCESS: 'GET_TODO_SUCCESS',
    GET_TODO_FAILURE: 'GET_TODO_FAILURE',
}
export default ActionTypes